1. Deleting elements from a DataFrame:
An index from your dataframe:
df.drop(3, inplace=True)# df , remove a row with index label 3

A column from your dataframe:
df.drop('column_to_remove', axis=1, inplace=True)
A row from your dataframe
there are many ways, one example is below
# Drop rows where 'State/Territory' is 'California' or 'Colorado' by filtering with a query
df = df.query("`State/Territory` != 'California' & `State/Territory` != 'Colorado'")

2. How do you iterate over a pandas dataframe?
for index, row in df.iterrows():
  print(index, row['State/Territory'])

3. How would you convert a string to a date?
df['date_column'] = pd.to_datetime(df['string_date_column'], format='%Y-%m-%d')
4. What is data aggregation?  Give an example in Python.
# calculates sum of sales per country
df.groupby('country').agg({'sales': 'sum'})

5. What is GroupBy in Pandas (groupby()). Give an example in Python.
Groupby split the data into groups based on some criteria, and then apply a function to each group independently.
#calculates the mean of the 'sales' column for each country,
df.groupby('country)['sales'].mean()

In [10]:
import pandas as pd
import numpy as np
import requests
from io import BytesIO

In [15]:
url='https://github.com/yinaS1234/data-608/raw/main/S1/2020_Presidential_Election_Results.xlsx'
df=pd.read_excel(url)
df.head()

,State/Territory,Biden Electoral Votes,Trump Electoral Votes,Biden Popular Vote,Trump Popular Vote
0,Alabama,0,9,849,1442
1,Alaska,0,3,153,189
2,Arizona,11,0,1672,1662
3,Arkansas,0,6,423,760
4,California,55,0,11110,6006

In [16]:
df.drop(0, inplace=True)
df

,State/Territory,Biden Electoral Votes,Trump Electoral Votes,Biden Popular Vote,Trump Popular Vote
1,Alaska,0,3,153,189
2,Arizona,11,0,1672,1662
3,Arkansas,0,6,423,760
4,California,55,0,11110,6006
5,Colorado,9,0,1805,1365
6,Connecticut,7,0,1083,714
7,Delaware,3,0,296,200
8,District of Columbia,3,0,317,18
9,Florida,29,0,5297,5669
10,Georgia,16,0,2474,2462
11,Hawaii,4,0,366,197
12,Idaho,0,4,287,554
13,Illinois,20,0,3476,2442
14,Indiana,0,11,1244,1729
15,Iowa,0,6,759,897
16,Kansas,0,6,570,772
17,Kentucky,0,8,772,1327
18,Louisiana,0,8,856,1256
19,Maine,3,1,435,360
20,Maryland,10,0,1985,976
21,Massachusetts,11,0,2388,1166
22,Michigan,16,0,2804,2649
23,Minnesota,10,0,1717,1484
24,Mississippi,0,6,539,756
25,Missouri,0,10,1253,1714
26,Montana,0,3,244,343
27,Nebraska,0,5,374,556
28,Nevada,6,0,703,669
29,New Hampshire,4,0,424,365
30,New Jersey,14,0,2608,1885
31,New Mexico,5,0,501,402
32,New York,29,0,5235,3256
33,North Carolina,15,0,2684,2759
34,North Dakota,0,3,114,235
35,Ohio,0,18,2679,3151
36,Oklahoma,0,7,503,1020
37,Oregon,7,0,1341,958
38,Pennsylvania,20,0,3459,3374
39,Rhode Island,4,0,307,199
40,South Carolina,0,9,1092,1386
41,South Dakota,0,3,150,261
42,Tennessee,0,11,1144,1854
43,Texas,0,38,5255,5890
44,Utah,0,6,560,865
45,Vermont,3,0,242,112
46,Virginia,13,0,2418,1962
47,Washington,12,0,2364,1581
48,West Virginia,0,5,235,545
49,Wisconsin,10,0,1630,1610
50,Wyoming,0,3,73,193

In [17]:
df.drop('Biden Electoral Votes', axis=1,inplace=True)
df

,State/Territory,Trump Electoral Votes,Biden Popular Vote,Trump Popular Vote
1,Alaska,3,153,189
2,Arizona,0,1672,1662
3,Arkansas,6,423,760
4,California,0,11110,6006
5,Colorado,0,1805,1365
6,Connecticut,0,1083,714
7,Delaware,0,296,200
8,District of Columbia,0,317,18
9,Florida,0,5297,5669
10,Georgia,0,2474,2462
11,Hawaii,0,366,197
12,Idaho,4,287,554
13,Illinois,0,3476,2442
14,Indiana,11,1244,1729
15,Iowa,6,759,897
16,Kansas,6,570,772
17,Kentucky,8,772,1327
18,Louisiana,8,856,1256
19,Maine,1,435,360
20,Maryland,0,1985,976
21,Massachusetts,0,2388,1166
22,Michigan,0,2804,2649
23,Minnesota,0,1717,1484
24,Mississippi,6,539,756
25,Missouri,10,1253,1714
26,Montana,3,244,343
27,Nebraska,5,374,556
28,Nevada,0,703,669
29,New Hampshire,0,424,365
30,New Jersey,0,2608,1885
31,New Mexico,0,501,402
32,New York,0,5235,3256
33,North Carolina,0,2684,2759
34,North Dakota,3,114,235
35,Ohio,18,2679,3151
36,Oklahoma,7,503,1020
37,Oregon,0,1341,958
38,Pennsylvania,0,3459,3374
39,Rhode Island,0,307,199
40,South Carolina,9,1092,1386
41,South Dakota,3,150,261
42,Tennessee,11,1144,1854
43,Texas,38,5255,5890
44,Utah,6,560,865
45,Vermont,0,242,112
46,Virginia,0,2418,1962
47,Washington,0,2364,1581
48,West Virginia,5,235,545
49,Wisconsin,0,1630,1610
50,Wyoming,3,73,193

In [22]:
df=df.query("`State/Territory`!='California' & `State/Territory`!='Colorado'")
df

,State/Territory,Trump Electoral Votes,Biden Popular Vote,Trump Popular Vote
1,Alaska,3,153,189
2,Arizona,0,1672,1662
3,Arkansas,6,423,760
6,Connecticut,0,1083,714
7,Delaware,0,296,200
8,District of Columbia,0,317,18
9,Florida,0,5297,5669
10,Georgia,0,2474,2462
11,Hawaii,0,366,197
12,Idaho,4,287,554
13,Illinois,0,3476,2442
14,Indiana,11,1244,1729
15,Iowa,6,759,897
16,Kansas,6,570,772
17,Kentucky,8,772,1327
18,Louisiana,8,856,1256
19,Maine,1,435,360
20,Maryland,0,1985,976
21,Massachusetts,0,2388,1166
22,Michigan,0,2804,2649
23,Minnesota,0,1717,1484
24,Mississippi,6,539,756
25,Missouri,10,1253,1714
26,Montana,3,244,343
27,Nebraska,5,374,556
28,Nevada,0,703,669
29,New Hampshire,0,424,365
30,New Jersey,0,2608,1885
31,New Mexico,0,501,402
32,New York,0,5235,3256
33,North Carolina,0,2684,2759
34,North Dakota,3,114,235
35,Ohio,18,2679,3151
36,Oklahoma,7,503,1020
37,Oregon,0,1341,958
38,Pennsylvania,0,3459,3374
39,Rhode Island,0,307,199
40,South Carolina,9,1092,1386
41,South Dakota,3,150,261
42,Tennessee,11,1144,1854
43,Texas,38,5255,5890
44,Utah,6,560,865
45,Vermont,0,242,112
46,Virginia,0,2418,1962
47,Washington,0,2364,1581
48,West Virginia,5,235,545
49,Wisconsin,0,1630,1610
50,Wyoming,3,73,193

In [21]:
df = df.query("`State/Territory` != 'California' & `State/Territory` != 'Colorado'")

In [26]:
for index, row in df.iterrows():
  print(index, row['State/Territory'])

1 Alaska
2 Arizona
3 Arkansas
6 Connecticut
7 Delaware
8 District of Columbia
9 Florida
10 Georgia
11 Hawaii
12 Idaho
13 Illinois
14 Indiana
15 Iowa
16 Kansas
17 Kentucky
18 Louisiana
19 Maine
20 Maryland
21 Massachusetts
22 Michigan
23 Minnesota
24 Mississippi
25 Missouri
26 Montana
27 Nebraska
28 Nevada
29 New Hampshire
30 New Jersey
31 New Mexico
32 New York
33 North Carolina
34 North Dakota
35 Ohio
36 Oklahoma
37 Oregon
38 Pennsylvania
39 Rhode Island
40 South Carolina
41 South Dakota
42 Tennessee
43 Texas
44 Utah
45 Vermont
46 Virginia
47 Washington
48 West Virginia
49 Wisconsin
50 Wyoming